In [3]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LinearRegression, Ridge
from sklearn.pipeline import Pipeline
from sklearn.metrics import mean_absolute_percentage_error
from sklearn.svm import SVR

from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from xgboost import XGBRegressor

import mlflow

In [4]:
# set the dagshub tracking server

mlflow.set_tracking_uri("https://dagshub.com/Anubhavspeaks01/uber-demand-prediction.mlflow")

In [5]:
import dagshub
dagshub.init(repo_owner='Anubhavspeaks01', repo_name='uber-demand-prediction', mlflow=True)

Accessing as Anubhavspeaks01

Initialized MLflow to track repo "Anubhavspeaks01/uber-demand-prediction"

Repository Anubhavspeaks01/uber-demand-prediction initialized!

In [6]:
# load the training and test data

train_data_path = "../data/processed/train.csv"
test_data_path = "../data/processed/test.csv"

train_df = pd.read_csv(train_data_path, parse_dates=["tpep_pickup_datetime"]).set_index("tpep_pickup_datetime")

test_df = pd.read_csv(test_data_path, parse_dates=["tpep_pickup_datetime"]).set_index("tpep_pickup_datetime")

train_df

,lag_1,lag_2,lag_3,lag_4,region,total_pickups,avg_pickups,day_of_week
tpep_pickup_datetime,,,,,,,,
2016-01-01 01:00:00,160.0,149.0,120.0,58.0,0,187,161.0,4
2016-01-01 01:15:00,187.0,160.0,149.0,120.0,0,194,175.0,4
2016-01-01 01:30:00,194.0,187.0,160.0,149.0,0,180,177.0,4
2016-01-01 01:45:00,180.0,194.0,187.0,160.0,0,197,185.0,4
2016-01-01 02:00:00,197.0,180.0,194.0,187.0,0,185,185.0,4
...,...,...,...,...,...,...,...,...
2016-02-29 22:45:00,15.0,9.0,11.0,11.0,29,12,12.0,0
2016-02-29 23:00:00,12.0,15.0,9.0,11.0,29,17,14.0,0
2016-02-29 23:15:00,17.0,12.0,15.0,9.0,29,15,14.0,0
2016-02-29 23:30:00,15.0,17.0,12.0,15.0,29,15,15.0,0
2016-02-29 23:45:00,15.0,15.0,17.0,12.0,29,12,14.0,0

In [7]:
# missing value in training data

train_df.isna().sum()

lag_1            0
lag_2            0
lag_3            0
lag_4            0
region           0
total_pickups    0
avg_pickups      0
day_of_week      0
dtype: int64

In [8]:
# missing values in the test data

test_df.isna().sum()

lag_1            0
lag_2            0
lag_3            0
lag_4            0
region           0
total_pickups    0
avg_pickups      0
day_of_week      0
dtype: int64

In [9]:
# make X_train and y_train

X_train = train_df.drop(columns=["total_pickups"])

y_train = train_df["total_pickups"]

In [10]:
X_train.head()

,lag_1,lag_2,lag_3,lag_4,region,avg_pickups,day_of_week
tpep_pickup_datetime,,,,,,,
2016-01-01 01:00:00,160.0,149.0,120.0,58.0,0,161.0,4
2016-01-01 01:15:00,187.0,160.0,149.0,120.0,0,175.0,4
2016-01-01 01:30:00,194.0,187.0,160.0,149.0,0,177.0,4
2016-01-01 01:45:00,180.0,194.0,187.0,160.0,0,185.0,4
2016-01-01 02:00:00,197.0,180.0,194.0,187.0,0,185.0,4

In [11]:
# make X_test and y_test

X_test = test_df.drop(columns=["total_pickups"])

y_test = test_df["total_pickups"]

In [12]:
X_test.head()

,lag_1,lag_2,lag_3,lag_4,region,avg_pickups,day_of_week
tpep_pickup_datetime,,,,,,,
2016-03-01 00:00:00,36.0,44.0,31.0,29.0,0,39.0,1
2016-03-01 00:15:00,41.0,36.0,44.0,31.0,0,37.0,1
2016-03-01 00:30:00,35.0,41.0,36.0,44.0,0,41.0,1
2016-03-01 00:45:00,47.0,35.0,41.0,36.0,0,38.0,1
2016-03-01 01:00:00,34.0,47.0,35.0,41.0,0,35.0,1

In [13]:
from sklearn import set_config

set_config(transform_output="pandas")

In [14]:
# encode the data

encoder = ColumnTransformer([
    ("ohe", OneHotEncoder(drop="first",sparse_output=False), ["region","day_of_week"])
], remainder="passthrough", n_jobs=-1,force_int_remainder_cols=False)

In [15]:
encoder

ColumnTransformer(force_int_remainder_cols=False, n_jobs=-1,
                  remainder='passthrough',
                  transformers=[('ohe',
                                 OneHotEncoder(drop='first',
                                               sparse_output=False),
                                 ['region', 'day_of_week'])])

In [18]:
# encode the train and test data

X_train_encoded = encoder.fit_transform(X_train)
X_test_encoded = encoder.transform(X_test)

/Users/anubhavsingh/Uber_Demand_Prediction/.conda/lib/python3.14/site-packages/sklearn/compose/_column_transformer.py:978: FutureWarning: The parameter `force_int_remainder_cols` is deprecated and will be removed in 1.9. It has no effect. Leave it to its default value to avoid this warning.
  warnings.warn(

In [19]:
import optuna
import tqdm

/Users/anubhavsingh/Uber_Demand_Prediction/.conda/lib/python3.14/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [20]:
# set the experiment

mlflow.set_experiment("Model Selection")

2026/03/03 23:06:08 INFO mlflow.tracking.fluent: Experiment with name 'Model Selection' does not exist. Creating a new experiment.

<Experiment: artifact_location='mlflow-artifacts:/55f071ca609e4033bf5000c54815bd97', creation_time=1772559368994, experiment_id='1', last_update_time=1772559368994, lifecycle_stage='active', name='Model Selection', tags={}, workspace='default'>

In [21]:
def objective(trial):
    # start the child run
    with mlflow.start_run(nested=True) as child:
        
        # model name search space
        list_of_models = ["LR", "RF", "GBR", "XGBR"]
        model_name = trial.suggest_categorical("model_name", list_of_models)
    
        if model_name == "LR":
            model = LinearRegression()
    
        elif model_name == "RF":
            n_estimators_rf = trial.suggest_int("n_estimators_rf",10,100,step=10)
            max_depth_rf = trial.suggest_int("max_depth_rf",3,10)
            model = RandomForestRegressor(n_estimators=n_estimators_rf, 
                                          max_depth=max_depth_rf, 
                                          random_state=42, n_jobs=-1)
    
        elif model_name == "GBR":
            n_estimators_gb = trial.suggest_int("n_estimators_gb",10,100,step=10)
            learning_rate_gb = trial.suggest_float("learning_rate_gb",1e-4,1e-1, log=True)
            model = GradientBoostingRegressor(n_estimators=n_estimators_gb, 
                                              learning_rate=learning_rate_gb,
                                             random_state=42)
    
        elif model_name == "XGBR":
            n_estimators_xgb = trial.suggest_int("n_estimators_xgb",10,100,step=10)
            learning_rate_xgb = trial.suggest_float("learning_rate_xgb",1e-4,1e-1, log=True)
            max_depth_xgb = trial.suggest_int("max_depth_xgb",3,10)
            model = XGBRegressor(n_estimators=n_estimators_xgb,
                                learning_rate=learning_rate_xgb,
                                max_depth=max_depth_xgb)
    
        # log the model name
        mlflow.log_param("model_name",model_name)
        
        # log the model parameters
        mlflow.log_params(model.get_params())
        
        # fit on the data
        model.fit(X_train_encoded,y_train)
    
        # get the predictions
        y_pred = model.predict(X_test_encoded)
    
        # calculate the loss
        loss = mean_absolute_percentage_error(y_test, y_pred)
    
        # log the metric
        mlflow.log_metric("MAPE",loss)
        return loss

In [22]:
# optimize the objective function

with mlflow.start_run(run_name="best_model", nested=True) as parent:

    # create a study object
    study = optuna.create_study(study_name="model_selection", direction="minimize")
    # optimize the objective function
    study.optimize(func=objective, n_trials=50, n_jobs=-1)
    
    # log the best parameters
    mlflow.log_params(study.best_params)
    # log the best error value
    mlflow.log_metric("Best_MAPE", study.best_value)

[I 2026-03-03 23:06:34,903] A new study created in memory with name: model_selection

🏃 View run adaptable-shad-254 at: https://dagshub.com/Anubhavspeaks01/uber-demand-prediction.mlflow/#/experiments/1/runs/4dea72a3c8104489b0efc81733b10527
🧪 View experiment at: https://dagshub.com/Anubhavspeaks01/uber-demand-prediction.mlflow/#/experiments/1

[I 2026-03-03 23:07:06,579] Trial 0 finished with value: 0.17680868983106915 and parameters: {'model_name': 'RF', 'n_estimators_rf': 80, 'max_depth_rf': 7}. Best is trial 0 with value: 0.17680868983106915.

🏃 View run painted-auk-191 at: https://dagshub.com/Anubhavspeaks01/uber-demand-prediction.mlflow/#/experiments/1/runs/1fcc41b6ba3d4280be41171f2321740e
🧪 View experiment at: https://dagshub.com/Anubhavspeaks01/uber-demand-prediction.mlflow/#/experiments/1
🏃 View run beautiful-hog-81 at: https://dagshub.com/Anubhavspeaks01/uber-demand-prediction.mlflow/#/experiments/1/runs/fbde3c2bbd9a44958f448b5f6ba1475f
🧪 View experiment at: https://dagshub.com/Anubhavspeaks01/uber-demand-prediction.mlflow/#/experiments/1
🏃 View run industrious-newt-458 at: https://dagshub.com/Anubhavspeaks01/uber-demand-prediction.mlflow/#/experiments/1/runs/b77a8222bc9641ac93c0017d369acdac
🧪 View experiment at: https://dagshub.com/Anubhavspeaks01/uber-demand-prediction.mlflow/#/experiments/1
🏃 View run receptive-zebra-925 at: https://dagshub.com/Anubhavspeaks01/uber-demand-prediction.mlflow/#/experiments/1/runs/87fe58b0f0a9432f91267d7ccb8f36f2
🧪 View experiment at: https://dagshub.com/Anubhavspeaks01/uber-demand-prediction.mlflow/#/experiments/1
🏃 View run efficient-dove-600 at: https://dagshub.com/Anubhavspeaks01/uber-demand-prediction.mlflow/#/experiments/1/runs/48943cdf2f6d44e1b861ddce93e17af6
🧪 View experiment at: https://dagshub.com/Anubhavspeaks01/uber-demand-prediction.mlflow/#/experiments/1
🏃 View run handsome-rook-950 at: https://dagshub.com/Anubhavspeaks01/uber-demand-prediction.mlflow/#/experiments/1/runs/acdef3c52f96469cae7bc213963f991a
🧪 View experiment at: https://dagshub.com/Anubhavspeaks01/uber-demand-prediction.mlflow/#/experiments/1
🏃 View run luminous-hawk-911 at: https://dagshub.com/Anubhavspeaks01/uber-demand-prediction.mlflow/#/experiments/1/runs/88256e60bbc34c74a9beb22fe951c418
🧪 View experiment at: https://dagshub.com/Anubhavspeaks01/uber-demand-prediction.mlflow/#/experiments/1
🏃 View run amazing-bug-850 at: https://dagshub.com/Anubhavspeaks01/uber-demand-prediction.mlflow/#/experiments/1/runs/fe704547a2e04f6b95700f0b73e631a8
🧪 View experiment at: https://dagshub.com/Anubhavspeaks01/uber-demand-prediction.mlflow/#/experiments/1
🏃 View run legendary-bear-141 at: https://dagshub.com/Anubhavspeaks01/uber-demand-prediction.mlflow/#/experiments/1/runs/c079752759aa4be7ab691c7d5d77bb05
🧪 View experiment at: https://dagshub.com/Anubhavspeaks01/uber-demand-prediction.mlflow/#/experiments/1

[I 2026-03-03 23:07:17,554] Trial 7 finished with value: 6.074960368426332 and parameters: {'model_name': 'GBR', 'n_estimators_gb': 10, 'learning_rate_gb': 0.008419107163414175}. Best is trial 0 with value: 0.17680868983106915.
[I 2026-03-03 23:07:18,555] Trial 6 finished with value: 0.07934790285463009 and parameters: {'model_name': 'LR'}. Best is trial 6 with value: 0.07934790285463009.
[I 2026-03-03 23:07:19,566] Trial 9 finished with value: 1.1672030300157346 and parameters: {'model_name': 'GBR', 'n_estimators_gb': 30, 'learning_rate_gb': 0.06345398142589752}. Best is trial 6 with value: 0.07934790285463009.
[I 2026-03-03 23:07:20,570] Trial 3 finished with value: 2.086867570877075 and parameters: {'model_name': 'XGBR', 'n_estimators_xgb': 100, 'learning_rate_xgb': 0.011737315506753757, 'max_depth_xgb': 6}. Best is trial 6 with value: 0.07934790285463009.
[I 2026-03-03 23:07:21,594] Trial 4 finished with value: 3.3144915103912354 and parameters: {'model_name': 'XGBR', 'n_estimators_xgb': 30, 'learning_rate_xgb': 0.022976304633047, 'max_depth_xgb': 10}. Best is trial 6 with value: 0.07934790285463009.
[I 2026-03-03 23:07:22,563] Trial 1 finished with value: 0.07934790285463009 and parameters: {'model_name': 'LR'}. Best is trial 6 with value: 0.07934790285463009.
[I 2026-03-03 23:07:23,642] Trial 8 finished with value: 0.07934790285463009 and parameters: {'model_name': 'LR'}. Best is trial 6 with value: 0.07934790285463009.
[I 2026-03-03 23:07:24,563] Trial 5 finished with value: 0.07934790285463009 and parameters: {'model_name': 'LR'}. Best is trial 6 with value: 0.07934790285463009.
[I 2026-03-03 23:07:25,549] Trial 2 finished with value: 0.07934790285463009 and parameters: {'model_name': 'LR'}. Best is trial 6 with value: 0.07934790285463009.

🏃 View run selective-eel-521 at: https://dagshub.com/Anubhavspeaks01/uber-demand-prediction.mlflow/#/experiments/1/runs/73e114fae04d469b95f7c6906c60a3d0
🧪 View experiment at: https://dagshub.com/Anubhavspeaks01/uber-demand-prediction.mlflow/#/experiments/1

[I 2026-03-03 23:08:06,652] Trial 10 finished with value: 2.3341305255889893 and parameters: {'model_name': 'XGBR', 'n_estimators_xgb': 90, 'learning_rate_xgb': 0.011713582913277025, 'max_depth_xgb': 7}. Best is trial 6 with value: 0.07934790285463009.

🏃 View run redolent-cub-852 at: https://dagshub.com/Anubhavspeaks01/uber-demand-prediction.mlflow/#/experiments/1/runs/c7df972c08574eaf9607780dd62a033b
🧪 View experiment at: https://dagshub.com/Anubhavspeaks01/uber-demand-prediction.mlflow/#/experiments/1
🏃 View run receptive-donkey-510 at: https://dagshub.com/Anubhavspeaks01/uber-demand-prediction.mlflow/#/experiments/1/runs/eb6d39607af544ebb7530d2b973dcdf8
🧪 View experiment at: https://dagshub.com/Anubhavspeaks01/uber-demand-prediction.mlflow/#/experiments/1
🏃 View run useful-fox-632 at: https://dagshub.com/Anubhavspeaks01/uber-demand-prediction.mlflow/#/experiments/1/runs/2f0f890e2e8348718918ba25a926a9aa
🧪 View experiment at: https://dagshub.com/Anubhavspeaks01/uber-demand-prediction.mlflow/#/experiments/1
🏃 View run rumbling-toad-469 at: https://dagshub.com/Anubhavspeaks01/uber-demand-prediction.mlflow/#/experiments/1/runs/6969f4ace8c24e1d890c7bc17f0f2f34
🧪 View experiment at: https://dagshub.com/Anubhavspeaks01/uber-demand-prediction.mlflow/#/experiments/1
🏃 View run skillful-asp-523 at: https://dagshub.com/Anubhavspeaks01/uber-demand-prediction.mlflow/#/experiments/1/runs/67743e9329294774ab7ed042268a2b93
🧪 View experiment at: https://dagshub.com/Anubhavspeaks01/uber-demand-prediction.mlflow/#/experiments/1
🏃 View run ambitious-bee-472 at: https://dagshub.com/Anubhavspeaks01/uber-demand-prediction.mlflow/#/experiments/1/runs/eb4872037a97498a8f8ddfedd65ac7d3
🧪 View experiment at: https://dagshub.com/Anubhavspeaks01/uber-demand-prediction.mlflow/#/experiments/1
🏃 View run bouncy-crow-827 at: https://dagshub.com/Anubhavspeaks01/uber-demand-prediction.mlflow/#/experiments/1/runs/4008a4d7ac934df58b5d81030f05acb7
🧪 View experiment at: https://dagshub.com/Anubhavspeaks01/uber-demand-prediction.mlflow/#/experiments/1
🏃 View run amazing-ram-139 at: https://dagshub.com/Anubhavspeaks01/uber-demand-prediction.mlflow/#/experiments/1/runs/12f5c0fd7e194229b5bd52e22cdfd8ce
🧪 View experiment at: https://dagshub.com/Anubhavspeaks01/uber-demand-prediction.mlflow/#/experiments/1
🏃 View run upset-owl-96 at: https://dagshub.com/Anubhavspeaks01/uber-demand-prediction.mlflow/#/experiments/1/runs/5d38545017a14b43964ba7cdb9d5b496
🧪 View experiment at: https://dagshub.com/Anubhavspeaks01/uber-demand-prediction.mlflow/#/experiments/1

[I 2026-03-03 23:08:17,606] Trial 11 finished with value: 0.5365101844163557 and parameters: {'model_name': 'RF', 'n_estimators_rf': 10, 'max_depth_rf': 3}. Best is trial 6 with value: 0.07934790285463009.
[I 2026-03-03 23:08:18,631] Trial 12 finished with value: 0.5365101844163557 and parameters: {'model_name': 'RF', 'n_estimators_rf': 10, 'max_depth_rf': 3}. Best is trial 6 with value: 0.07934790285463009.
[I 2026-03-03 23:08:19,563] Trial 13 finished with value: 0.5365101844163557 and parameters: {'model_name': 'RF', 'n_estimators_rf': 10, 'max_depth_rf': 3}. Best is trial 6 with value: 0.07934790285463009.
[I 2026-03-03 23:08:20,559] Trial 14 finished with value: 0.5365101844163557 and parameters: {'model_name': 'RF', 'n_estimators_rf': 10, 'max_depth_rf': 3}. Best is trial 6 with value: 0.07934790285463009.
[I 2026-03-03 23:08:21,582] Trial 15 finished with value: 0.5426613001489775 and parameters: {'model_name': 'RF', 'n_estimators_rf': 20, 'max_depth_rf': 3}. Best is trial 6 with value: 0.07934790285463009.
[I 2026-03-03 23:08:22,560] Trial 16 finished with value: 0.5365101844163557 and parameters: {'model_name': 'RF', 'n_estimators_rf': 10, 'max_depth_rf': 3}. Best is trial 6 with value: 0.07934790285463009.
[I 2026-03-03 23:08:23,556] Trial 17 finished with value: 0.5365101844163557 and parameters: {'model_name': 'RF', 'n_estimators_rf': 10, 'max_depth_rf': 3}. Best is trial 6 with value: 0.07934790285463009.
[I 2026-03-03 23:08:24,683] Trial 18 finished with value: 0.5365101844163557 and parameters: {'model_name': 'RF', 'n_estimators_rf': 10, 'max_depth_rf': 3}. Best is trial 6 with value: 0.07934790285463009.
[I 2026-03-03 23:08:25,551] Trial 19 finished with value: 0.5365101844163557 and parameters: {'model_name': 'RF', 'n_estimators_rf': 10, 'max_depth_rf': 3}. Best is trial 6 with value: 0.07934790285463009.

🏃 View run funny-frog-546 at: https://dagshub.com/Anubhavspeaks01/uber-demand-prediction.mlflow/#/experiments/1/runs/b42ccf9205c34ac9a8fd9ccfa0ee1e85
🧪 View experiment at: https://dagshub.com/Anubhavspeaks01/uber-demand-prediction.mlflow/#/experiments/1

[I 2026-03-03 23:09:06,656] Trial 20 finished with value: 0.07934790285463009 and parameters: {'model_name': 'LR'}. Best is trial 6 with value: 0.07934790285463009.

🏃 View run able-perch-753 at: https://dagshub.com/Anubhavspeaks01/uber-demand-prediction.mlflow/#/experiments/1/runs/57530cf92d1c4f689a719aa3c56aad55
🧪 View experiment at: https://dagshub.com/Anubhavspeaks01/uber-demand-prediction.mlflow/#/experiments/1
🏃 View run exultant-cow-769 at: https://dagshub.com/Anubhavspeaks01/uber-demand-prediction.mlflow/#/experiments/1/runs/12ff92be360d48fcada012999eed19cd
🧪 View experiment at: https://dagshub.com/Anubhavspeaks01/uber-demand-prediction.mlflow/#/experiments/1
🏃 View run auspicious-mule-348 at: https://dagshub.com/Anubhavspeaks01/uber-demand-prediction.mlflow/#/experiments/1/runs/a90de1a206e64f06a11ca3050cb8f93c
🧪 View experiment at: https://dagshub.com/Anubhavspeaks01/uber-demand-prediction.mlflow/#/experiments/1
🏃 View run gentle-kit-498 at: https://dagshub.com/Anubhavspeaks01/uber-demand-prediction.mlflow/#/experiments/1/runs/22e64a62df8c4b4c8a7a2318789a4299
🧪 View experiment at: https://dagshub.com/Anubhavspeaks01/uber-demand-prediction.mlflow/#/experiments/1
🏃 View run persistent-lamb-870 at: https://dagshub.com/Anubhavspeaks01/uber-demand-prediction.mlflow/#/experiments/1/runs/2768119e7aa044ad8eae7ccbe5214c89
🧪 View experiment at: https://dagshub.com/Anubhavspeaks01/uber-demand-prediction.mlflow/#/experiments/1
🏃 View run incongruous-panda-62 at: https://dagshub.com/Anubhavspeaks01/uber-demand-prediction.mlflow/#/experiments/1/runs/546f6fc0b7a448058749a63bc5cf5dc2
🧪 View experiment at: https://dagshub.com/Anubhavspeaks01/uber-demand-prediction.mlflow/#/experiments/1
🏃 View run thundering-asp-663 at: https://dagshub.com/Anubhavspeaks01/uber-demand-prediction.mlflow/#/experiments/1/runs/b5fa03d42843423fa5addd472e2f0925
🧪 View experiment at: https://dagshub.com/Anubhavspeaks01/uber-demand-prediction.mlflow/#/experiments/1
🏃 View run shivering-goose-363 at: https://dagshub.com/Anubhavspeaks01/uber-demand-prediction.mlflow/#/experiments/1/runs/786f5f5c711e444a9bd2315e4e8c3222
🧪 View experiment at: https://dagshub.com/Anubhavspeaks01/uber-demand-prediction.mlflow/#/experiments/1
🏃 View run monumental-hare-324 at: https://dagshub.com/Anubhavspeaks01/uber-demand-prediction.mlflow/#/experiments/1/runs/ba71f0850aa749968042625b6dba02a9
🧪 View experiment at: https://dagshub.com/Anubhavspeaks01/uber-demand-prediction.mlflow/#/experiments/1

[I 2026-03-03 23:09:17,581] Trial 21 finished with value: 0.07934790285463009 and parameters: {'model_name': 'LR'}. Best is trial 6 with value: 0.07934790285463009.
[I 2026-03-03 23:09:18,638] Trial 22 finished with value: 0.07934790285463009 and parameters: {'model_name': 'LR'}. Best is trial 6 with value: 0.07934790285463009.
[I 2026-03-03 23:09:19,559] Trial 23 finished with value: 0.07934790285463009 and parameters: {'model_name': 'LR'}. Best is trial 6 with value: 0.07934790285463009.
[I 2026-03-03 23:09:20,584] Trial 24 finished with value: 0.07934790285463009 and parameters: {'model_name': 'LR'}. Best is trial 6 with value: 0.07934790285463009.
[I 2026-03-03 23:09:21,550] Trial 25 finished with value: 0.07934790285463009 and parameters: {'model_name': 'LR'}. Best is trial 6 with value: 0.07934790285463009.
[I 2026-03-03 23:09:22,564] Trial 26 finished with value: 0.07934790285463009 and parameters: {'model_name': 'LR'}. Best is trial 6 with value: 0.07934790285463009.
[I 2026-03-03 23:09:23,656] Trial 27 finished with value: 0.07934790285463009 and parameters: {'model_name': 'LR'}. Best is trial 6 with value: 0.07934790285463009.
[I 2026-03-03 23:09:24,553] Trial 28 finished with value: 0.07934790285463009 and parameters: {'model_name': 'LR'}. Best is trial 6 with value: 0.07934790285463009.
[I 2026-03-03 23:09:25,573] Trial 29 finished with value: 0.07934790285463009 and parameters: {'model_name': 'LR'}. Best is trial 6 with value: 0.07934790285463009.

🏃 View run angry-hen-750 at: https://dagshub.com/Anubhavspeaks01/uber-demand-prediction.mlflow/#/experiments/1/runs/44b0138d26724d36a4267905a624090c
🧪 View experiment at: https://dagshub.com/Anubhavspeaks01/uber-demand-prediction.mlflow/#/experiments/1

[I 2026-03-03 23:09:58,546] Trial 30 finished with value: 0.07934790285463009 and parameters: {'model_name': 'LR'}. Best is trial 6 with value: 0.07934790285463009.

🏃 View run learned-lark-571 at: https://dagshub.com/Anubhavspeaks01/uber-demand-prediction.mlflow/#/experiments/1/runs/7f0643e1b6734b229eb88c836eaaae0e
🧪 View experiment at: https://dagshub.com/Anubhavspeaks01/uber-demand-prediction.mlflow/#/experiments/1

[I 2026-03-03 23:10:01,577] Trial 38 finished with value: 0.07934790285463009 and parameters: {'model_name': 'LR'}. Best is trial 6 with value: 0.07934790285463009.

🏃 View run monumental-ape-202 at: https://dagshub.com/Anubhavspeaks01/uber-demand-prediction.mlflow/#/experiments/1/runs/3d4bd4bedd6a4744ab5de4f1371b5b5b
🧪 View experiment at: https://dagshub.com/Anubhavspeaks01/uber-demand-prediction.mlflow/#/experiments/1
🏃 View run clumsy-perch-195 at: https://dagshub.com/Anubhavspeaks01/uber-demand-prediction.mlflow/#/experiments/1/runs/8222fdc60dd243fc8e2e735f979a394d
🧪 View experiment at: https://dagshub.com/Anubhavspeaks01/uber-demand-prediction.mlflow/#/experiments/1

[I 2026-03-03 23:10:15,580] Trial 31 finished with value: 6.514424714040405 and parameters: {'model_name': 'GBR', 'n_estimators_gb': 100, 'learning_rate_gb': 0.00010222325242150538}. Best is trial 6 with value: 0.07934790285463009.

🏃 View run unruly-snipe-676 at: https://dagshub.com/Anubhavspeaks01/uber-demand-prediction.mlflow/#/experiments/1/runs/72ef5367a85c417fb12392f81497e9c5
🧪 View experiment at: https://dagshub.com/Anubhavspeaks01/uber-demand-prediction.mlflow/#/experiments/1
🏃 View run nimble-tern-520 at: https://dagshub.com/Anubhavspeaks01/uber-demand-prediction.mlflow/#/experiments/1/runs/efb213838ab8428e8b473133a12e5a84
🧪 View experiment at: https://dagshub.com/Anubhavspeaks01/uber-demand-prediction.mlflow/#/experiments/1
🏃 View run mysterious-quail-613 at: https://dagshub.com/Anubhavspeaks01/uber-demand-prediction.mlflow/#/experiments/1/runs/827f634c8368401884d44759d0e3acc6
🧪 View experiment at: https://dagshub.com/Anubhavspeaks01/uber-demand-prediction.mlflow/#/experiments/1
🏃 View run clumsy-dove-9 at: https://dagshub.com/Anubhavspeaks01/uber-demand-prediction.mlflow/#/experiments/1/runs/93d7f030129d4f669fc69c1a9193689b
🧪 View experiment at: https://dagshub.com/Anubhavspeaks01/uber-demand-prediction.mlflow/#/experiments/1

[I 2026-03-03 23:10:23,559] Trial 32 finished with value: 6.498344030749569 and parameters: {'model_name': 'GBR', 'n_estimators_gb': 100, 'learning_rate_gb': 0.00012844126609080447}. Best is trial 6 with value: 0.07934790285463009.

🏃 View run melodic-frog-781 at: https://dagshub.com/Anubhavspeaks01/uber-demand-prediction.mlflow/#/experiments/1/runs/2977603423454d7984df5891f958504b
🧪 View experiment at: https://dagshub.com/Anubhavspeaks01/uber-demand-prediction.mlflow/#/experiments/1
🏃 View run abundant-elk-204 at: https://dagshub.com/Anubhavspeaks01/uber-demand-prediction.mlflow/#/experiments/1/runs/78d9b0af1a5c4687bbb008fcd7ba8cc2
🧪 View experiment at: https://dagshub.com/Anubhavspeaks01/uber-demand-prediction.mlflow/#/experiments/1

[I 2026-03-03 23:10:27,655] Trial 33 finished with value: 6.513059383790179 and parameters: {'model_name': 'GBR', 'n_estimators_gb': 100, 'learning_rate_gb': 0.00010444611688473256}. Best is trial 6 with value: 0.07934790285463009.

🏃 View run fortunate-loon-840 at: https://dagshub.com/Anubhavspeaks01/uber-demand-prediction.mlflow/#/experiments/1/runs/d0467d57944141fd843499c0b11bae9b
🧪 View experiment at: https://dagshub.com/Anubhavspeaks01/uber-demand-prediction.mlflow/#/experiments/1

[I 2026-03-03 23:10:29,600] Trial 34 finished with value: 6.51132223156011 and parameters: {'model_name': 'GBR', 'n_estimators_gb': 100, 'learning_rate_gb': 0.00010727545670074237}. Best is trial 6 with value: 0.07934790285463009.
[I 2026-03-03 23:10:30,568] Trial 40 finished with value: 0.07934790285463009 and parameters: {'model_name': 'LR'}. Best is trial 6 with value: 0.07934790285463009.
[I 2026-03-03 23:10:31,653] Trial 35 finished with value: 6.498601925648461 and parameters: {'model_name': 'GBR', 'n_estimators_gb': 100, 'learning_rate_gb': 0.00012802005359688942}. Best is trial 6 with value: 0.07934790285463009.
[I 2026-03-03 23:10:33,555] Trial 36 finished with value: 6.497148271141851 and parameters: {'model_name': 'GBR', 'n_estimators_gb': 100, 'learning_rate_gb': 0.00013039019602269328}. Best is trial 6 with value: 0.07934790285463009.
[I 2026-03-03 23:10:35,648] Trial 37 finished with value: 6.482845069156309 and parameters: {'model_name': 'GBR', 'n_estimators_gb': 100, 'learning_rate_gb': 0.00015373813803036844}. Best is trial 6 with value: 0.07934790285463009.
[I 2026-03-03 23:10:37,547] Trial 39 finished with value: 6.5126989446890216 and parameters: {'model_name': 'GBR', 'n_estimators_gb': 100, 'learning_rate_gb': 0.00010503346434462613}. Best is trial 6 with value: 0.07934790285463009.

🏃 View run sincere-perch-433 at: https://dagshub.com/Anubhavspeaks01/uber-demand-prediction.mlflow/#/experiments/1/runs/d9972ab03cb24eb6b69ca2b5f737c783
🧪 View experiment at: https://dagshub.com/Anubhavspeaks01/uber-demand-prediction.mlflow/#/experiments/1

[I 2026-03-03 23:10:58,571] Trial 41 finished with value: 6.26145580410278 and parameters: {'model_name': 'GBR', 'n_estimators_gb': 100, 'learning_rate_gb': 0.000522626152637733}. Best is trial 6 with value: 0.07934790285463009.

🏃 View run industrious-colt-146 at: https://dagshub.com/Anubhavspeaks01/uber-demand-prediction.mlflow/#/experiments/1/runs/83502ccdf14f448e8cbd42a4149711d5
🧪 View experiment at: https://dagshub.com/Anubhavspeaks01/uber-demand-prediction.mlflow/#/experiments/1
🏃 View run fun-fowl-739 at: https://dagshub.com/Anubhavspeaks01/uber-demand-prediction.mlflow/#/experiments/1/runs/ff79ab18a8684c43bcc20932bc0a6ca4
🧪 View experiment at: https://dagshub.com/Anubhavspeaks01/uber-demand-prediction.mlflow/#/experiments/1

[I 2026-03-03 23:11:10,570] Trial 42 finished with value: 6.568100929260254 and parameters: {'model_name': 'XGBR', 'n_estimators_xgb': 10, 'learning_rate_xgb': 0.0001515661171155628, 'max_depth_xgb': 3}. Best is trial 6 with value: 0.07934790285463009.

🏃 View run suave-hog-334 at: https://dagshub.com/Anubhavspeaks01/uber-demand-prediction.mlflow/#/experiments/1/runs/6f25c02111c1410292e5b64cce954e7a
🧪 View experiment at: https://dagshub.com/Anubhavspeaks01/uber-demand-prediction.mlflow/#/experiments/1
🏃 View run languid-roo-4 at: https://dagshub.com/Anubhavspeaks01/uber-demand-prediction.mlflow/#/experiments/1/runs/5b2801b3d6844c9c826ee920753ba6fd
🧪 View experiment at: https://dagshub.com/Anubhavspeaks01/uber-demand-prediction.mlflow/#/experiments/1
🏃 View run skillful-grub-95 at: https://dagshub.com/Anubhavspeaks01/uber-demand-prediction.mlflow/#/experiments/1/runs/2bbca4e4613540069b0adaf4190b3459
🧪 View experiment at: https://dagshub.com/Anubhavspeaks01/uber-demand-prediction.mlflow/#/experiments/1
🏃 View run persistent-perch-98 at: https://dagshub.com/Anubhavspeaks01/uber-demand-prediction.mlflow/#/experiments/1/runs/71b75de3278f4caaaefff53d54280429
🧪 View experiment at: https://dagshub.com/Anubhavspeaks01/uber-demand-prediction.mlflow/#/experiments/1

[I 2026-03-03 23:11:16,561] Trial 43 finished with value: 6.571044921875 and parameters: {'model_name': 'XGBR', 'n_estimators_xgb': 10, 'learning_rate_xgb': 0.00010402349747662487, 'max_depth_xgb': 3}. Best is trial 6 with value: 0.07934790285463009.

🏃 View run funny-gull-190 at: https://dagshub.com/Anubhavspeaks01/uber-demand-prediction.mlflow/#/experiments/1/runs/aaf3309bb89e4968848819ccedc29131
🧪 View experiment at: https://dagshub.com/Anubhavspeaks01/uber-demand-prediction.mlflow/#/experiments/1
🏃 View run invincible-grouse-1 at: https://dagshub.com/Anubhavspeaks01/uber-demand-prediction.mlflow/#/experiments/1/runs/84d42b3c231e4f9aab50a33605c28034
🧪 View experiment at: https://dagshub.com/Anubhavspeaks01/uber-demand-prediction.mlflow/#/experiments/1

[I 2026-03-03 23:11:19,558] Trial 44 finished with value: 6.569861888885498 and parameters: {'model_name': 'XGBR', 'n_estimators_xgb': 10, 'learning_rate_xgb': 0.00012312566550149118, 'max_depth_xgb': 3}. Best is trial 6 with value: 0.07934790285463009.
[I 2026-03-03 23:11:20,570] Trial 45 finished with value: 6.562217712402344 and parameters: {'model_name': 'XGBR', 'n_estimators_xgb': 10, 'learning_rate_xgb': 0.0002466465114207907, 'max_depth_xgb': 3}. Best is trial 6 with value: 0.07934790285463009.
[I 2026-03-03 23:11:21,563] Trial 46 finished with value: 6.571047782897949 and parameters: {'model_name': 'XGBR', 'n_estimators_xgb': 10, 'learning_rate_xgb': 0.00010397735071606895, 'max_depth_xgb': 3}. Best is trial 6 with value: 0.07934790285463009.
[I 2026-03-03 23:11:22,563] Trial 47 finished with value: 6.569599628448486 and parameters: {'model_name': 'XGBR', 'n_estimators_xgb': 10, 'learning_rate_xgb': 0.000127358934952697, 'max_depth_xgb': 3}. Best is trial 6 with value: 0.07934790285463009.
[I 2026-03-03 23:11:23,551] Trial 48 finished with value: 6.568103313446045 and parameters: {'model_name': 'XGBR', 'n_estimators_xgb': 10, 'learning_rate_xgb': 0.00015152686743216708, 'max_depth_xgb': 3}. Best is trial 6 with value: 0.07934790285463009.
[I 2026-03-03 23:11:24,579] Trial 49 finished with value: 6.5707502365112305 and parameters: {'model_name': 'XGBR', 'n_estimators_xgb': 10, 'learning_rate_xgb': 0.00010878297584597315, 'max_depth_xgb': 3}. Best is trial 6 with value: 0.07934790285463009.

🏃 View run best_model at: https://dagshub.com/Anubhavspeaks01/uber-demand-prediction.mlflow/#/experiments/1/runs/1d55608b95d04696828cd35f71932067
🧪 View experiment at: https://dagshub.com/Anubhavspeaks01/uber-demand-prediction.mlflow/#/experiments/1

In [23]:
# best value

study.best_value

0.07934790285463009

In [24]:
# best parameters

study.best_params

{'model_name': 'LR'}

In [25]:
# model value counts

study.trials_dataframe()['params_model_name'].value_counts()

params_model_name
LR      18
XGBR    11
GBR     11
RF      10
Name: count, dtype: int64

In [28]:
from optuna.visualization import (
    plot_optimization_history, 
    plot_parallel_coordinate, 
    plot_param_importances
)

In [29]:
!pip install plotly

Requirement already satisfied: plotly in /opt/anaconda3/lib/python3.13/site-packages (6.3.0)
Requirement already satisfied: narwhals>=1.15.1 in /opt/anaconda3/lib/python3.13/site-packages (from plotly) (2.7.0)
Requirement already satisfied: packaging in /opt/anaconda3/lib/python3.13/site-packages (from plotly) (25.0)

In [32]:
# train the linear regression model

lr = LinearRegression()

lr.fit(X_train_encoded, y_train)

# get predictions
y_pred_train = lr.predict(X_train_encoded) 
y_pred_test = lr.predict(X_test_encoded)

# loss

mape_train = mean_absolute_percentage_error(y_train, y_pred_train)
mape_test = mean_absolute_percentage_error(y_test, y_pred_test)

print("The training error is ", mape_train)
print("The test error is ", mape_test)

The training error is  0.08778013304566377
The test error is  0.07934790285463009

In [33]:
lr.coef_

array([-2.33737604,  0.71512405, -0.55601505, -1.25311068, -3.20463231,
       -0.86685973, -2.79925402, -3.62516859,  0.41386463, -2.9376376 ,
       -1.97624678, -3.75050442,  0.51806283, -2.54033388, -2.43297463,
        0.47632075,  0.61254786, -4.7417372 , -2.03077217, -1.26960984,
       -4.03690273, -2.08863167, -1.0414428 ,  0.73561736, -0.99999442,
       -0.85944985, -2.43098478,  0.67112238,  0.57385071, -0.11719951,
       -0.28045898, -0.37180749, -0.5238324 , -0.4233113 , -0.34045774,
       -0.54170892, -0.36264553, -0.2493965 , -0.31905518,  2.4912456 ])

In [34]:
def tune_ridge(trial):
    # hyperparameter space
    alpha = trial.suggest_float("alpha",30,100)
    
    # make the model object
    ridge = Ridge(alpha=alpha, random_state=42)
    
    # train the model
    ridge.fit(X_train_encoded, y_train)
    
    # get predictions
    y_pred = ridge.predict(X_test_encoded)
    
    # calculate loss
    loss = mean_absolute_percentage_error(y_test, y_pred)

    return loss

In [35]:
# create study

study = optuna.create_study(study_name="tune_model", direction="minimize")

[I 2026-03-03 23:15:41,116] A new study created in memory with name: tune_model

In [36]:
# optimize

study.optimize(func=tune_ridge, n_trials=100, n_jobs=-1, show_progress_bar=True)

Best trial: 14. Best value: 0.0791642:  18%|███████▋                                   | 18/100 [00:00<00:01, 41.87it/s]

[I 2026-03-03 23:15:55,905] Trial 0 finished with value: 0.07921058672920982 and parameters: {'alpha': 66.50078155882879}. Best is trial 0 with value: 0.07921058672920982.
[I 2026-03-03 23:15:55,926] Trial 1 finished with value: 0.07917216689141483 and parameters: {'alpha': 93.56000769552267}. Best is trial 1 with value: 0.07917216689141483.
[I 2026-03-03 23:15:55,932] Trial 7 finished with value: 0.07921194072062233 and parameters: {'alpha': 65.62034294367048}. Best is trial 1 with value: 0.07917216689141483.
[I 2026-03-03 23:15:55,934] Trial 5 finished with value: 0.07916665471768947 and parameters: {'alpha': 97.90282135743836}. Best is trial 5 with value: 0.07916665471768947.
[I 2026-03-03 23:15:55,935] Trial 3 finished with value: 0.0792610042537362 and parameters: {'alpha': 37.3427493794714}. Best is trial 5 with value: 0.07916665471768947.
[I 2026-03-03 23:15:55,935] Trial 6 finished with value: 0.07918211308441897 and parameters: {'alpha': 86.10911170147904}. Best is trial 5 with value: 0.07916665471768947.
[I 2026-03-03 23:15:55,937] Trial 4 finished with value: 0.07923644525076347 and parameters: {'alpha': 50.638287650778565}. Best is trial 5 with value: 0.07916665471768947.
[I 2026-03-03 23:15:55,938] Trial 2 finished with value: 0.0791983536331519 and parameters: {'alpha': 74.6828768341051}. Best is trial 5 with value: 0.07916665471768947.
[I 2026-03-03 23:15:55,938] Trial 8 finished with value: 0.07924884388067704 and parameters: {'alpha': 43.72895662784599}. Best is trial 5 with value: 0.07916665471768947.
[I 2026-03-03 23:15:55,939] Trial 9 finished with value: 0.07924707573969343 and parameters: {'alpha': 44.67660974372117}. Best is trial 5 with value: 0.07916665471768947.
[I 2026-03-03 23:15:56,027] Trial 10 finished with value: 0.07916422795558538 and parameters: {'alpha': 99.86771268288972}. Best is trial 10 with value: 0.07916422795558538.
[I 2026-03-03 23:15:56,030] Trial 12 finished with value: 0.07916517546637766 and parameters: {'alpha': 99.09654036814253}. Best is trial 10 with value: 0.07916422795558538.
[I 2026-03-03 23:15:56,032] Trial 11 finished with value: 0.07916430003923472 and parameters: {'alpha': 99.80899726606596}. Best is trial 10 with value: 0.07916422795558538.
[I 2026-03-03 23:15:56,033] Trial 13 finished with value: 0.07916524000186273 and parameters: {'alpha': 99.04421958922013}. Best is trial 10 with value: 0.07916422795558538.
[I 2026-03-03 23:15:56,033] Trial 14 finished with value: 0.0791641655894888 and parameters: {'alpha': 99.91851494253976}. Best is trial 14 with value: 0.0791641655894888.
[I 2026-03-03 23:15:56,038] Trial 15 finished with value: 0.07916792353440769 and parameters: {'alpha': 96.88648268542175}. Best is trial 14 with value: 0.0791641655894888.
[I 2026-03-03 23:15:56,039] Trial 16 finished with value: 0.07916472458230844 and parameters: {'alpha': 99.46327494163987}. Best is trial 14 with value: 0.0791641655894888.
[I 2026-03-03 23:15:56,059] Trial 17 finished with value: 0.07916455777985806 and parameters: {'alpha': 99.59907845707528}. Best is trial 14 with value: 0.0791641655894888.
[I 2026-03-03 23:15:56,070] Trial 18 finished with value: 0.07916489564886227 and parameters: {'alpha': 99.32401548600794}. Best is trial 14 with value: 0.0791641655894888.

[I 2026-03-03 23:15:56,098] Trial 19 finished with value: 0.0791827815198209 and parameters: {'alpha': 85.61939200851275}. Best is trial 14 with value: 0.0791641655894888.
[I 2026-03-03 23:15:56,111] Trial 21 finished with value: 0.07918693662601725 and parameters: {'alpha': 82.62079237741276}. Best is trial 14 with value: 0.0791641655894888.
[I 2026-03-03 23:15:56,128] Trial 20 finished with value: 0.07918561771932539 and parameters: {'alpha': 83.56511406834807}. Best is trial 14 with value: 0.0791641655894888.
[I 2026-03-03 23:15:56,139] Trial 22 finished with value: 0.07918669276519878 and parameters: {'alpha': 82.79473121612709}. Best is trial 14 with value: 0.0791641655894888.
[I 2026-03-03 23:15:56,142] Trial 23 finished with value: 0.0791875221387122 and parameters: {'alpha': 82.20496825076945}. Best is trial 14 with value: 0.0791641655894888.
[I 2026-03-03 23:15:56,151] Trial 24 finished with value: 0.07918358140800967 and parameters: {'alpha': 85.03594011849569}. Best is trial 14 with value: 0.0791641655894888.
[I 2026-03-03 23:15:56,155] Trial 25 finished with value: 0.07918241318993244 and parameters: {'alpha': 85.88882162596512}. Best is trial 14 with value: 0.0791641655894888.
[I 2026-03-03 23:15:56,157] Trial 26 finished with value: 0.07918534713130342 and parameters: {'alpha': 83.75966000999436}. Best is trial 14 with value: 0.0791641655894888.
[I 2026-03-03 23:15:56,178] Trial 27 finished with value: 0.07919307893746456 and parameters: {'alpha': 78.30572487637308}. Best is trial 14 with value: 0.0791641655894888.
[I 2026-03-03 23:15:56,225] Trial 29 finished with value: 0.07917698966934943 and parameters: {'alpha': 89.90672431341108}. Best is trial 14 with value: 0.0791641655894888.
[I 2026-03-03 23:15:56,225] Trial 30 finished with value: 0.07917462619094333 and parameters: {'alpha': 91.68659275685768}. Best is trial 14 with value: 0.0791641655894888.
[I 2026-03-03 23:15:56,233] Trial 28 finished with value: 0.07917453408749706 and parameters: {'alpha': 91.75632949590253}. Best is trial 14 with value: 0.0791641655894888.
[I 2026-03-03 23:15:56,247] Trial 32 finished with value: 0.07917506751524268 and parameters: {'alpha': 91.35250134610625}. Best is trial 14 with value: 0.0791641655894888.
[I 2026-03-03 23:15:56,252] Trial 31 finished with value: 0.07917569295146769 and parameters: {'alpha': 90.88023226854165}. Best is trial 14 with value: 0.0791641655894888.
[I 2026-03-03 23:15:56,256] Trial 33 finished with value: 0.07917536582066166 and parameters: {'alpha': 91.12714706020422}. Best is trial 14 with value: 0.0791641655894888.
[I 2026-03-03 23:15:56,267] Trial 34 finished with value: 0.0791760419587403 and parameters: {'alpha': 90.61727866881861}. Best is trial 14 with value: 0.0791641655894888.
[I 2026-03-03 23:15:56,281] Trial 35 finished with value: 0.07917289004700906 and parameters: {'alpha': 93.00631465279845}. Best is trial 14 with value: 0.0791641655894888.
[I 2026-03-03 23:15:56,290] Trial 36 finished with value: 0.07922683135729881 and parameters: {'alpha': 56.307868416902856}. Best is trial 14 with value: 0.0791641655894888.

[I 2026-03-03 23:15:56,321] Trial 37 finished with value: 0.07920323547976689 and parameters: {'alpha': 71.37788487952209}. Best is trial 14 with value: 0.0791641655894888.
[I 2026-03-03 23:15:56,325] Trial 38 finished with value: 0.07920348636057263 and parameters: {'alpha': 71.20928740366095}. Best is trial 14 with value: 0.0791641655894888.
[I 2026-03-03 23:15:56,341] Trial 39 finished with value: 0.07922220093357538 and parameters: {'alpha': 59.13063496091481}. Best is trial 14 with value: 0.0791641655894888.
[I 2026-03-03 23:15:56,353] Trial 40 finished with value: 0.07920723955234298 and parameters: {'alpha': 68.70366879656828}. Best is trial 14 with value: 0.0791641655894888.
[I 2026-03-03 23:15:56,355] Trial 41 finished with value: 0.07922003912026787 and parameters: {'alpha': 60.47624505152477}. Best is trial 14 with value: 0.0791641655894888.
[I 2026-03-03 23:15:56,363] Trial 42 finished with value: 0.07920524552783303 and parameters: {'alpha': 70.03009133561477}. Best is trial 14 with value: 0.0791641655894888.
[I 2026-03-03 23:15:56,370] Trial 43 finished with value: 0.0791958974601175 and parameters: {'alpha': 76.36301029139655}. Best is trial 14 with value: 0.0791641655894888.
[I 2026-03-03 23:15:56,378] Trial 44 finished with value: 0.07916980174977632 and parameters: {'alpha': 95.3954539306707}. Best is trial 14 with value: 0.0791641655894888.
[I 2026-03-03 23:15:56,419] Trial 45 finished with value: 0.07927328865895317 and parameters: {'alpha': 31.191309067111497}. Best is trial 14 with value: 0.0791641655894888.
[I 2026-03-03 23:15:56,433] Trial 46 finished with value: 0.0791692239009557 and parameters: {'alpha': 95.85346741357029}. Best is trial 14 with value: 0.0791641655894888.
[I 2026-03-03 23:15:56,447] Trial 47 finished with value: 0.07916938656234035 and parameters: {'alpha': 95.72435605349636}. Best is trial 14 with value: 0.0791641655894888.
[I 2026-03-03 23:15:56,451] Trial 48 finished with value: 0.07916949259420356 and parameters: {'alpha': 95.6402121964864}. Best is trial 14 with value: 0.0791641655894888.
[I 2026-03-03 23:15:56,461] Trial 49 finished with value: 0.07916962407976418 and parameters: {'alpha': 95.53587940679569}. Best is trial 14 with value: 0.0791641655894888.
[I 2026-03-03 23:15:56,462] Trial 50 finished with value: 0.07916976108077077 and parameters: {'alpha': 95.42727299186913}. Best is trial 14 with value: 0.0791641655894888.
[I 2026-03-03 23:15:56,473] Trial 51 finished with value: 0.07927489247100399 and parameters: {'alpha': 30.407172755708224}. Best is trial 14 with value: 0.0791641655894888.
[I 2026-03-03 23:15:56,486] Trial 52 finished with value: 0.07917082794271461 and parameters: {'alpha': 94.59400289632804}. Best is trial 14 with value: 0.0791641655894888.
[I 2026-03-03 23:15:56,501] Trial 53 finished with value: 0.07916430968698866 and parameters: {'alpha': 99.80113894110426}. Best is trial 14 with value: 0.0791641655894888.
[I 2026-03-03 23:15:56,514] Trial 54 finished with value: 0.07916647054223053 and parameters: {'alpha': 98.05120953591272}. Best is trial 14 with value: 0.0791641655894888.

Best trial: 56. Best value: 0.0791641:  69%|█████████████████████████████▋             | 69/100 [00:01<00:00, 77.28it/s]

[I 2026-03-03 23:15:56,533] Trial 56 finished with value: 0.07916409456914995 and parameters: {'alpha': 99.97636931097053}. Best is trial 56 with value: 0.07916409456914995.
[I 2026-03-03 23:15:56,539] Trial 55 finished with value: 0.07916429651112501 and parameters: {'alpha': 99.81187100635644}. Best is trial 56 with value: 0.07916409456914995.
[I 2026-03-03 23:15:56,559] Trial 57 finished with value: 0.07916453704267415 and parameters: {'alpha': 99.61596670367804}. Best is trial 56 with value: 0.07916409456914995.
[I 2026-03-03 23:15:56,570] Trial 59 finished with value: 0.07916452484650159 and parameters: {'alpha': 99.62589930784239}. Best is trial 56 with value: 0.07916409456914995.
[I 2026-03-03 23:15:56,576] Trial 58 finished with value: 0.07916432759467652 and parameters: {'alpha': 99.78655283418702}. Best is trial 56 with value: 0.07916409456914995.
[I 2026-03-03 23:15:56,598] Trial 60 finished with value: 0.07916451045941524 and parameters: {'alpha': 99.6376162972613}. Best is trial 56 with value: 0.07916409456914995.
[I 2026-03-03 23:15:56,607] Trial 61 finished with value: 0.07917926993634804 and parameters: {'alpha': 88.20839094330724}. Best is trial 56 with value: 0.07916409456914995.
[I 2026-03-03 23:15:56,610] Trial 62 finished with value: 0.07916420613286357 and parameters: {'alpha': 99.88548882650403}. Best is trial 56 with value: 0.07916409456914995.
[I 2026-03-03 23:15:56,637] Trial 63 finished with value: 0.07917982009689434 and parameters: {'alpha': 87.80058535143428}. Best is trial 56 with value: 0.07916409456914995.
[I 2026-03-03 23:15:56,646] Trial 64 finished with value: 0.07917799286065293 and parameters: {'alpha': 89.1580307496148}. Best is trial 56 with value: 0.07916409456914995.
[I 2026-03-03 23:15:56,648] Trial 65 finished with value: 0.07918044352061725 and parameters: {'alpha': 87.3392753484662}. Best is trial 56 with value: 0.07916409456914995.
[I 2026-03-03 23:15:56,672] Trial 66 finished with value: 0.07917929215511599 and parameters: {'alpha': 88.19190507634069}. Best is trial 56 with value: 0.07916409456914995.
[I 2026-03-03 23:15:56,681] Trial 67 finished with value: 0.07917888730836217 and parameters: {'alpha': 88.49236944767986}. Best is trial 56 with value: 0.07916409456914995.
[I 2026-03-03 23:15:56,689] Trial 68 finished with value: 0.07917982398173143 and parameters: {'alpha': 87.79770963218648}. Best is trial 56 with value: 0.07916409456914995.
[I 2026-03-03 23:15:56,717] Trial 70 finished with value: 0.07917272811457583 and parameters: {'alpha': 93.13026670165016}. Best is trial 56 with value: 0.07916409456914995.

Best trial: 80. Best value: 0.0791641:  86%|████████████████████████████████████▉      | 86/100 [00:01<00:00, 76.15it/s]

[I 2026-03-03 23:15:56,718] Trial 69 finished with value: 0.0791670863406222 and parameters: {'alpha': 97.55530581917145}. Best is trial 56 with value: 0.07916409456914995.
[I 2026-03-03 23:15:56,734] Trial 71 finished with value: 0.07917216589157156 and parameters: {'alpha': 93.56077347566725}. Best is trial 56 with value: 0.07916409456914995.
[I 2026-03-03 23:15:56,757] Trial 72 finished with value: 0.07916706956092376 and parameters: {'alpha': 97.56880975762081}. Best is trial 56 with value: 0.07916409456914995.
[I 2026-03-03 23:15:56,770] Trial 74 finished with value: 0.0791719741477185 and parameters: {'alpha': 93.70786969813119}. Best is trial 56 with value: 0.07916409456914995.
[I 2026-03-03 23:15:56,781] Trial 73 finished with value: 0.07917281076082183 and parameters: {'alpha': 93.06699964814244}. Best is trial 56 with value: 0.07916409456914995.
[I 2026-03-03 23:15:56,792] Trial 76 finished with value: 0.07916738115730143 and parameters: {'alpha': 97.31938189565568}. Best is trial 56 with value: 0.07916409456914995.
[I 2026-03-03 23:15:56,799] Trial 75 finished with value: 0.07916735383988913 and parameters: {'alpha': 97.34121106381497}. Best is trial 56 with value: 0.07916409456914995.
[I 2026-03-03 23:15:56,810] Trial 77 finished with value: 0.07916743328894302 and parameters: {'alpha': 97.27775410283763}. Best is trial 56 with value: 0.07916409456914995.
[I 2026-03-03 23:15:56,831] Trial 78 finished with value: 0.0791673326286229 and parameters: {'alpha': 97.35816111805337}. Best is trial 56 with value: 0.07916409456914995.
[I 2026-03-03 23:15:56,848] Trial 79 finished with value: 0.07916676609235651 and parameters: {'alpha': 97.81311963629568}. Best is trial 56 with value: 0.07916409456914995.
[I 2026-03-03 23:15:56,852] Trial 80 finished with value: 0.07916406685151742 and parameters: {'alpha': 99.99894929734239}. Best is trial 80 with value: 0.07916406685151742.
[I 2026-03-03 23:15:56,882] Trial 82 finished with value: 0.07923571123313794 and parameters: {'alpha': 51.06281721737492}. Best is trial 80 with value: 0.07916406685151742.
[I 2026-03-03 23:15:56,889] Trial 81 finished with value: 0.07916658987713772 and parameters: {'alpha': 97.95506063545626}. Best is trial 80 with value: 0.07916406685151742.
[I 2026-03-03 23:15:56,892] Trial 83 finished with value: 0.07919057172903472 and parameters: {'alpha': 80.05919847555327}. Best is trial 80 with value: 0.07916406685151742.
[I 2026-03-03 23:15:56,902] Trial 84 finished with value: 0.07919100247499723 and parameters: {'alpha': 79.75739951873555}. Best is trial 80 with value: 0.07916406685151742.
[I 2026-03-03 23:15:56,920] Trial 85 finished with value: 0.07916413030952515 and parameters: {'alpha': 99.94725426298233}. Best is trial 80 with value: 0.07916406685151742.
[I 2026-03-03 23:15:56,941] Trial 86 finished with value: 0.0791644447697271 and parameters: {'alpha': 99.69111605270054}. Best is trial 80 with value: 0.07916406685151742.

Best trial: 80. Best value: 0.0791641: 100%|██████████████████████████████████████████| 100/100 [00:01<00:00, 73.41it/s]

[I 2026-03-03 23:15:56,950] Trial 88 finished with value: 0.07916410557187112 and parameters: {'alpha': 99.96740613505735}. Best is trial 80 with value: 0.07916406685151742.
[I 2026-03-03 23:15:56,951] Trial 87 finished with value: 0.0791648789653811 and parameters: {'alpha': 99.33759625462254}. Best is trial 80 with value: 0.07916406685151742.
[I 2026-03-03 23:15:56,988] Trial 91 finished with value: 0.07917136310396239 and parameters: {'alpha': 94.17888794710079}. Best is trial 80 with value: 0.07916406685151742.
[I 2026-03-03 23:15:56,991] Trial 89 finished with value: 0.07916437407135372 and parameters: {'alpha': 99.74869761633673}. Best is trial 80 with value: 0.07916406685151742.
[I 2026-03-03 23:15:56,991] Trial 90 finished with value: 0.07916527457707347 and parameters: {'alpha': 99.01618939794163}. Best is trial 80 with value: 0.07916406685151742.
[I 2026-03-03 23:15:57,018] Trial 92 finished with value: 0.07917119216648517 and parameters: {'alpha': 94.31145628826495}. Best is trial 80 with value: 0.07916406685151742.
[I 2026-03-03 23:15:57,023] Trial 93 finished with value: 0.07917444976620105 and parameters: {'alpha': 91.82017773257006}. Best is trial 80 with value: 0.07916406685151742.
[I 2026-03-03 23:15:57,028] Trial 94 finished with value: 0.07917097352683428 and parameters: {'alpha': 94.48105752878723}. Best is trial 80 with value: 0.07916406685151742.
[I 2026-03-03 23:15:57,043] Trial 95 finished with value: 0.07917037945954504 and parameters: {'alpha': 94.94386693668875}. Best is trial 80 with value: 0.07916406685151742.
[I 2026-03-03 23:15:57,051] Trial 96 finished with value: 0.0791740761782083 and parameters: {'alpha': 92.10327987869205}. Best is trial 80 with value: 0.07916406685151742.
[I 2026-03-03 23:15:57,064] Trial 97 finished with value: 0.07916908844299658 and parameters: {'alpha': 95.96099671084409}. Best is trial 80 with value: 0.07916406685151742.
[I 2026-03-03 23:15:57,079] Trial 98 finished with value: 0.0791687650009784 and parameters: {'alpha': 96.21779091186154}. Best is trial 80 with value: 0.07916406685151742.
[I 2026-03-03 23:15:57,079] Trial 99 finished with value: 0.07916981040081224 and parameters: {'alpha': 95.38868554054262}. Best is trial 80 with value: 0.07916406685151742.

In [37]:
# best parameters

study.best_params

{'alpha': 99.99894929734239}

In [38]:
# best value

study.best_value

0.07916406685151742